CREATE TABLE individual (
  species_cd VARCHAR(20) NOT NULL,
  id VARCHAR(20) NOT NULL,
  male_parent_id VARCHAR(20),
  female_parent_id VARCHAR(20),
  morph VARCHAR(50),
  bloodline VARCHAR(50),
  gender_category CHAR(1),
  breeding_category CHAR(1),
  breeder VARCHAR(20),
  clutch_date DATE,
  hatch_date DATE,
  purchase_from VARCHAR(255),
  purchase_price DECIMAL(15,2),
  purchase_date DATE,
  sales_category VARCHAR(20),
  sales_to VARCHAR(255),
  sales_price_tax_ex DECIMAL(15,2),
  sales_price_tax DECIMAL(15,2),
  sales_price_tax_in DECIMAL(15,2),
  sales_date DATE,
  death_date DATE,
  note VARCHAR(255),
  create_user VARCHAR(20) NOT NULL,
  create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_user VARCHAR(20),
  update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (species_cd, id)
);
