CREATE TABLE individual (
  species_cd VARCHAR(10) NOT NULL,
  id VARCHAR(20) NOT NULL,
  morph VARCHAR(100) NOT NULL,
  gender CHAR(1) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (species_cd, id)
);
