openapi: 3.0.0
info:
  title: Individual Management API
  version: 1.0.0

paths:
  /individuals:
    get:
      summary: 個体情報一覧を取得
      responses:
        '200':
          description: 一覧取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Individual'

  /individuals/{species_cd}/{id}:
    put:
      summary: 個体情報を更新
      parameters:
        - in: path
          name: species_cd
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Individual'
      responses:
        '200':
          description: 更新成功

    delete:
      summary: 個体情報を論理削除
      parameters:
        - in: path
          name: species_cd
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 削除成功

components:
  schemas:
    Individual:
      type: object
      properties:
        species_cd:
          type: string
          maxLength: 20
        id:
          type: string
          maxLength: 20
        male_parent_id:
          type: string
          maxLength: 20
          nullable: true
        female_parent_id:
          type: string
          maxLength: 20
          nullable: true
        morph:
          type: string
          maxLength: 50
          nullable: true
        bloodline:
          type: string
          maxLength: 50
          nullable: true
        gender_category:
          type: string
          maxLength: 1
          nullable: true
        breeding_category:
          type: string
          maxLength: 1
          nullable: true
        breeder:
          type: string
          maxLength: 20
          nullable: true
        clutch_date:
          type: string
          format: date
          nullable: true
        hatch_date:
          type: string
          format: date
          nullable: true
        purchase_from:
          type: string
          nullable: true
        purchase_price:
          type: number
          format: double
          nullable: true
        purchase_date:
          type: string
          format: date
          nullable: true
        sales_category:
          type: string
          nullable: true
        sales_to:
          type: string
          nullable: true
        sales_price_tax_ex:
          type: number
          format: double
          nullable: true
        sales_price_tax:
          type: number
          format: double
          nullable: true
        sales_price_tax_in:
          type: number
          format: double
          nullable: true
        sales_date:
          type: string
          format: date
          nullable: true
        death_date:
          type: string
          format: date
          nullable: true
        note:
          type: string
          maxLength: 255
          nullable: true
        create_user:
          type: string
          maxLength: 20
        create_at:
          type: string
          format: date-time
        update_user:
          type: string
          maxLength: 20
          nullable: true
        update_at:
          type: string
          format: date-time
          nullable: true
      required:
        - species_cd
        - id
        - create_user
        - create_at