openapi: 3.0.1
info:
  title: MyApp API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Returns a greeting
      operationId: getHello
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
components:
  schemas:
    HelloResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
